clear
addpath(genpath(pwd))

%% Set Pars
CHAIN_LENGTH = 5000;
CHAIN_REP = 9;
N_CHAINS = 10;

DATE = "2021-04-16";
REGION = "wash";
PARAMETER_SET = "MMWR";
LIKELIHOOD_TYPE = "LL";
N_VARS = 5;
            

%% RUN
DATE = strcat(DATE);
MCMC_find_optimal_parms_for_region(DATE, REGION, PARAMETER_SET, LIKELIHOOD_TYPE, N_VARS, CHAIN_LENGTH, CHAIN_REP, N_CHAINS);
MCMC_Generate_Figures(DATE, REGION, PARAMETER_SET, LIKELIHOOD_TYPE, N_VARS, 1); % Only plot the first chain
MCMC_write_outputs(DATE, REGION, PARAMETER_SET, LIKELIHOOD_TYPE, N_VARS);



load("OUTPUT\2021-04-16_MCMCRun_nyc_MMWR_LL_NVarsFit5.mat")
temp1 = [RES_OUT{1}{1}.rejected ...
    RES_OUT{2}{1}.rejected ...
    RES_OUT{3}{1}.rejected ...
    RES_OUT{4}{1}.rejected ...
    RES_OUT{5}{1}.rejected ...
    RES_OUT{6}{1}.rejected ...
    RES_OUT{7}{1}.rejected ...
    RES_OUT{8}{1}.rejected ...
    RES_OUT{9}{1}.rejected ...
    RES_OUT{10}{1}.rejected]

load("OUTPUT\2021-04-16_MCMCRun_sflor_MMWR_LL_NVarsFit5.mat")
temp2 = [RES_OUT{1}{1}.rejected ...
    RES_OUT{2}{1}.rejected ...
    RES_OUT{3}{1}.rejected ...
    RES_OUT{4}{1}.rejected ...
    RES_OUT{5}{1}.rejected ...
    RES_OUT{6}{1}.rejected ...
    RES_OUT{7}{1}.rejected ...
    RES_OUT{8}{1}.rejected ...
    RES_OUT{9}{1}.rejected ...
    RES_OUT{10}{1}.rejected]

load("OUTPUT\2021-04-16_MCMCRun_wash_MMWR_LL_NVarsFit5.mat")
temp3 = [RES_OUT{1}{1}.rejected ...
    RES_OUT{2}{1}.rejected ...
    RES_OUT{3}{1}.rejected ...
    RES_OUT{4}{1}.rejected ...
    RES_OUT{5}{1}.rejected ...
    RES_OUT{6}{1}.rejected ...
    RES_OUT{7}{1}.rejected ...
    RES_OUT{8}{1}.rejected ...
    RES_OUT{9}{1}.rejected ...
    RES_OUT{10}{1}.rejected]